#Docker Composeのバージョン
version: '3'
#作成するコンテナを定義
services:
    nginx:
        build: ./nginx
        #ホスト側の81番ポートとコンテナ側の80番ポートをつなげる
        ports:
            - 81:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        #元になるDockerfileがおいてあるパスを指定
        build: ./php-fpm
        #プログラムソースディレクトリをマウント
        volumes:
            - ./source:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: asakatsu
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
    redis:
        image: redis:latest
        ports:
            - 6379:6379 
