version: '3'
services:
    nginx:
        build: ./nginx
        ports: 
            - 8082:80
        volumes: 
            - ./source:/usr/share/nginx/html
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html
